trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.7'
  displayName: 'Select Ruby version'

- script: |
    gem install bundler
    cd fastlane
    bundle install
  displayName: 'Install Bundler and Gems'

- script: |
    bundle exec fastlane ios release
  displayName: 'Build and Upload iOS App via Fastlane'
  env:
    APP_STORE_CONNECT_API_KEY_ID: $(APP_STORE_CONNECT_API_KEY_ID)
    APP_STORE_CONNECT_API_ISSUER_ID: $(APP_STORE_CONNECT_API_ISSUER_ID)
    APP_STORE_CONNECT_API_KEY_CONTENT: $(APP_STORE_CONNECT_API_KEY_CONTENT)
